---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Deploy 'tic-tac-toe'
      k8s:
        state: present
        definition: "{{ item }}"
        kubeconfig: "{{ kubeconfig }}"
        wait: true
      loop: "{{ lookup('file', 'kube_template/deploy_k8s.yml') | from_yaml_all | list }}"
      no_log: false