---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Ensure kind is present locally
      command: |
        export PATH="$(go env GOPATH)/bin/kind:$PATH"
        kind

    - name: Build a kind cluster locally
      command: |
        export PATH="$(go env GOPATH)/bin/kind:$PATH"
        kind create cluster --wait 300 --name molecule-test --kubeconfig {{ kubeconfig }}
      changed_when: true