---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Ensure kind is present locally
      command: >-
        kind --version
      register: kind_result
      failed_when: "kind_result.rc != 0 or 'kind version' not in kind_result.stdout"

    - name: Build a kind cluster locally
      shell: |
        kind create cluster --wait 300s --name molecule-test
      changed_when: true
      register: test

    - debug:
        var: test

    - name: Backup and update current kubeconfig
      shell: |
        mv  ~/.kube ~/.kube.bak
        mkdir ~/.kube
        cp -i ./~/.kube/config ~/.kube/config
        chown $(id -u):$(id -g) ~/.kube/config

    - name: test kind cluster config
      command: |
        cat {{ kubeconfig }}
      register: k

    - debug:
        var: k