---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Ensure kind is present locally
      command: >-
        kind --version
      register: kind_result
      failed_when: "kind_result.rc != 0 or 'kind version' not in kind_result.stdout"

    - debug:
        var: kind_result

    - name: Destroy a kind cluster locally
      command: |
        kind delete cluster --name molecule-test
      changed_when: false

    - name: Check backedup kubeconfig exist
      stat:
        path: ~/.kube.bak
      register: test_bak_config_exist

    - debug:
        var: test_bak_config_exist

    - name: Delete current kube folder if backup folder exists
      file:
        path: ~/.kube
        state: absent
      when: test_bak_config_exist.stat.exists and test_bak_config_exist.stat.isdir

    - name: Restore original kubeconfig if backup folder exists
      shell: |
        mv ~/.kube.bak ~/.kube
        export KUBECONFIG="{{ kubeconfig }}"
      register: test
      when: test_bak_config_exist.stat.exists and test_bak_config_exist.stat.isdir

    - name: Clean up current directory kubeconfig created by kind
      file:
        path: ./~
        state: absent
