---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Ensure kind is present locally
      command: >-
        kind --version
      register: kind_result
      failed_when: "kind_result.rc != 0 or 'kind version' not in kind_result.stdout"

    - debug:
        var: kind_result

    - name: Destroy a kind cluster locally
      command: |
        kind delete cluster --name molecule-test --kubeconfig {{ kubeconfig }}
      changed_when: false