---
# dependency:
#   name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: tic-tac-toe-molecule-test
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        molecule_no_log: false
  env:
    KUBECONFIG: ~/.kube/config
    K8S_AUTH_KUBECONFIG: ~/.kube/config
# verifier:
#   name: ansible
