---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: andeslam2019/tic-tac-toe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tic-tac-toe
